-- Database schema for AI Exterior project

CREATE DATABASE exterior_ai;
GO
USE exterior_ai;
GO

-- Users table
CREATE TABLE Users (
  Id BIGINT IDENTITY PRIMARY KEY,
  Email NVARCHAR(191) NOT NULL UNIQUE,
  PasswordHash NVARCHAR(255) NOT NULL,
  Role NVARCHAR(20) DEFAULT N'user',
  CreatedAt DATETIME2 DEFAULT SYSDATETIME()
);

-- Profiles table
CREATE TABLE Profiles (
  Id BIGINT IDENTITY PRIMARY KEY,
  UserId BIGINT NOT NULL,
  AreaSqm INT NULL,
  HouseType NVARCHAR(100) NULL,    
  Style NVARCHAR(200) NULL,        
  Budget NVARCHAR(50) NULL,
  UpdatedAt DATETIME2 DEFAULT SYSDATETIME(),
  FOREIGN KEY (UserId) REFERENCES Users(Id)
);

-- Generations table
CREATE TABLE Generations (
  Id BIGINT IDENTITY PRIMARY KEY,
  UserId BIGINT NOT NULL,
  InputDesc NVARCHAR(MAX) NULL,
  InputImageUrl NVARCHAR(500) NULL,
  OutputImageUrl NVARCHAR(500) NULL,
  Style NVARCHAR(200) NULL,
  Palette NVARCHAR(200) NULL,
  Seed BIGINT NULL,
  PromptUsed NVARCHAR(MAX) NULL,
  CreatedAt DATETIME2 DEFAULT SYSDATETIME(),
  FOREIGN KEY (UserId) REFERENCES Users(Id)
);
